config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"



  resources :offers
  resource :profile, only: [:show, :edit, :update]

  namespace :profile do
    resources :pepeatobookings, only: [:index, :show]
    resources :bookings, only: [:index, :show, :create, :new]
    resources :pepeatcommunity
    resources :offers
    resources :recipes do
      member do
        patch :like
      end

      resources :ingredients
      resources :categories
    end
  end

end

app/controllers/profile/bookings_controller.rb
module Profile
  class BookingsController < ApplicationController
    before_action :authenticate_user!
     #si je suis un utilisateur lambda


    def index
      @bookings = current_user.bookings.all

    end

    def show
      @booking = current_user.bookings.find(params[:id])
      @markers = Gmaps4rails.build_markers(@booking) do |booking, marker|
      marker.lat booking.offer.recipe.user.latitude
      marker.lng booking.offer.recipe.user.longitude
      end
    end


     def new
      @offer = Offer.find(params[:booking][:offer_id])
      @offer = recipe.offers
      @booking = Booking.new
    end

    def create
      @offer = Offer.find(params[:booking][:offer_id])
      @booking = @offer.bookings.build(booking_params)
      @booking.user = current_user
      @booking.save
      if @booking.save
        redirect_to profile_bookings_path
      else
        render :new
      end
    end

    def booking_params
      params.require(:booking).permit(:quantity, :offer_id)

    end

  end
end

app/controllers/profile/offers_controller.rb
module Profile
  class OffersController < ApplicationController
    def index
      @offers = Offer.all
    end
    def new

      @offer = Offer.new
    end
    def create
       @offer = current_user.offers.new(offer_params)

      if @offer.save
        redirect_to profile_recipes_path
      else
        render :new
      end
    end

    def destroy
      @offer = current_user.offers.find(params[:id])
      @offer.destroy
      redirect_to profile_recipes_path
    end

    def offer_params
       params.require(:offer).permit(:recipe_id, :startdate, :enddate, :portion, :delay, :price)
    end
  end
end

app/controllers/profile/pepeatcommunity_controller.rb
module Profile
  class PepeatcommunityController < ApplicationController
    def index
      @recipes = Recipe.all
    end
  end
end

app/controllers/profile/pepeatobookings_controller.rb
module Profile
  class PepeatobookingsController < ApplicationController
    before_action :authenticate_user!

#si je suis un pepeato

    def index
      @offers = current_user.offers.all
      @pepeatobookings = current_user.bookings.all
    end

    def show
      @pepeatobooking = current_user.bookings.find(params[:id])
    end
  end
end

app/controllers/profile/recipes_controller.rb
module Profile
  class RecipesController < ApplicationController

    before_action :authenticate_user!
    before_action :set_recipe, only: [:show, :edit, :destroy, :update, :like]

    def index
      @recipes = current_user.recipes
      @offer = Offer.new

    end

    def show
      @user = current_user
    end

    def create
      if params[:recipe][:id]
        @old_recipe = Recipe.find(params[:recipe][:id])
        @recipe = @old_recipe.dup
        @recipe.user = current_user
      else
        @recipe = current_user.recipes.new(recipe_params)
      end

      @recipe.save
      if @recipe.save

        if params[:recipe][:id]
          @recipe.picture = @old_recipe.picture
          @recipe.save
        end

        redirect_to profile_recipes_path
      else
        render :new
      end
    end

    def new
      @recipe = Recipe.new
    end


    def edit
    end

    def update
      @recipe.update(recipe_params)
      if @recipe.save
        redirect_to profile_recipes_path
      else
        render :edit

      end
    end

    def destroy
      @recipe.destroy
      redirect_to profile_recipes_path
    end

    def like
      @recipe.rank ||= 0
      @recipe.rank += 1

      if @recipe.save
        flash[:notice] = "Miam ! Merci pour le like !"
      else
        flash[:notice] = "Une erreur est survenu !"
      end

      redirect_to profile_recipe_path(@recipe)
    end


    private

    def set_recipe
      @recipe = current_user.recipes.find(params[:id])
    end

    def recipe_params
      params.require(:recipe).permit(:id,:name, :numberpers, :description, :cooktime, :preparationtime, :price, :halal, :casher, :bio, :gluten, :lactose, :vegan, :vegetarian, :picture, :rank)
    end

  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_user
  before_action :authenticate_user!


  def show

  end

  def edit
  end

  def update
    @user.update(user_params)
    if @user.save
      redirect_to profile_path
    else
      render :edit
    end

   # autocomplete


# fin autocomplete
  end

  def set_user
    @user = current_user
  end

  def user_params
    params.require(:user).permit(:firstname, :lastname, :phonenumber, :address, :city, :description, :delay, :email, :sex, :picture)
  end
end

app/views/profiles/edit.html.erb
<%= render 'shared/small_navbar' %>

<div class= "padded-top padded-bottom bg">
  <div class="container">
    <div class="row">
      <%= simple_form_for(@user, url: profile_path, html: { multipart: true }) do |f| %>
        <%= f.error_notification %>
        <div class=" col-xs-12 col-sm-8 col-sm-offset-2">
          <table id="profile-edit">
            <tr class="border">
              <td><b><%= f.input :firstname %></b></td>
              <td><b><%= f.input :lastname %></b></td>
            </tr>
            <tr>
              <td><b>  <%= f.input :address%></b></td>
              <td><b> <%= f.input :city, input_html: {id: "locality"} %></b></td>
            </tr>
             <tr>
              <td><b> <%= f.input :email %></b></td>
              <td><b><%= f.input :phonenumber %></b></td>
            </tr>
            <tr>
              <td><b><%= f.input :sex %></b></td>
              <td><%= f.file_field :picture %></td>
            </tr>
            <tr>
              <td colspan="2"><b> <%= f.input :description %></b></td>
            </tr>
            <tr id="submit-padd">
              <td colspan="2"><em><strong><%= f.button :submit, "GO!", class: "swagbtn btn-lg btn-danger" %></strong></em></td>
            </tr>
          </table>
      <% end %>
      </div>
    </div>
  </div>
</div>

app/views/profiles/show.html.erb
<%= render 'shared/small_navbar' %>

<div class="padded-top padded-bottom" id="profile">
  <div class="container">
    <div class="row">

      <div class="col-xs-12 col-sm-offset-3 col-sm-6">
        <div>
          <%=image_tag current_user.picture.url(:medium), class: "img-circle" %>
        </div>
        <table>
          <tr>
            <td><b>Prénom</b></td>
            <td><%= current_user.firstname %></td>
          </tr>
          <tr>
            <td><b>Nom</b></td>
            <td><%= current_user.lastname %></td>
          </tr>
          <tr>
            <td><b>Addresse</b></td>
            <td><%= current_user.address %></td>
          </tr>
          <tr>
            <td><b>Mail</b></td>
            <td><%= current_user.email %></td>
          </tr>
          <tr>
            <td><b>Numero</b></td>
            <td><%= current_user.phonenumber %></td>
          </tr>
          <tr>
            <td><b>Sexe</b></td>
            <td><%= current_user.sex %></td>
          </tr>
          <tr>
            <td><b>Description</b></td>
            <td><%= current_user.description %></td>
          </tr>
          <tr>
            <td colspan="2"><%= link_to 'edit', edit_profile_path, class: "btn btn-danger btn-lg swagbtn"%></td>
          </tr>
        </table>
      </div>
    </div>
  </div>
</div>