config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"



  resources :offers
  resource :profile, only: [:show, :edit, :update]

  namespace :profile do
    resources :pepeatobookings, only: [:index, :show]
    resources :bookings, only: [:index, :show, :create, :new]
    resources :pepeatcommunity
    resources :offers
    resources :recipes do
      member do
        patch :like
      end

      resources :ingredients
      resources :categories
    end
  end

end

app/views/shared/_flashes.html.erb
      <% if notice %>
        <div class="alert alert-info alert-dismissible width-flash" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <%= notice %>
        </div>
      <% end %>
      <% if alert %>
        <div class="alert alert-warning alert-dismissible width-flash" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <%= alert %>
        </div>
      <% end %>

app/views/shared/_footer.html.erb
<div id="footer">
<p class="text-center">Souper Franky</p>
  <hr>
  <div class="container">
    <div class="row ">
      <div class="col-md-offset-4 col-xs-12 col-sm-1">
        <i class="fa fa-twitter coco"></i>
      </div>
      <div class="col-xs-12 col-sm-1">
        <i class="fa fa-instagram coco"></i>
      </div>
      <div class="col-xs-12 col-sm-1">
        <i class="fa fa-twitter coco"></i>
      </div>
      <div class="col-xs-12 col-sm-1">
        <i class="fa fa-google-plus coco"></i>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12">
        <p class="text-center marg">powered by Flo & John</p>
      </div>
    </div>
  </div>

</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default navbar-wagon" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">
        <%= image_tag "vector.png" %>
      </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li>
          </li>
          <li class="dropdown">
            <%= link_to "#", {class: "dropdown-toggle", "data-toggle" => "dropdown", "role" => "button", "aria-expanded" => "false"} do %>
              <% if current_user.picture_file_name %>
                <%= image_tag current_user.picture.url(:medium), class: "img-avatar" %>
              <% end %>
              Profile <span class="caret"></span>
            <% end %>
            <ul class="dropdown-menu" role="menu">
              <li>
                <% if current_user.pepeato == true %>
                  <%= link_to profile_path do %>
                    <i class="fa fa-user"></i> <%= t ".Ma cuisine", default: "Ma cuisine" %>
                  <% end %>
                <% else %>
                  <%= link_to profile_path do %>
                    <i class="fa fa-user"></i> <%= t ".Mon profil", default: "Mon profil" %>
                  <% end %>
                <% end %>
              </li>
              <li>
                <% if current_user.pepeato == true %>
                    <%= link_to profile_recipes_path do %>
                      <i class="fa fa-home"></i>  <%= t ".profile", default: "Mes recettes" %>
                    <% end %>
                  <% else %>
                    <%= link_to profile_bookings_path do %>
                      <i class="fa fa-home"></i>  <%= t(".profile", default: "Mes commandes")%>
                    <% end %>

                <% end %>
              </li>
              <li>
                <%= link_to destroy_user_session_path, method: :delete do %>
                  <i class="fa fa-sign-out"></i>  <%= t ".sign_out", default: "Sign out" %>
                <% end %>
              </li>
            </ul>
          </li>
        <% else %>
          <li>
            <%= link_to t(".Devenir Pepeato", default: "Devenir Pepeato"), new_user_registration_path(pepeato: true) %>
          </li>
          <li>
            <%= link_to t(".Devenir Utilisateur", default: "Devenir Utilisateur"), new_user_registration_path %>
          </li>
          <li>
            <%= link_to t(".sign_in", default: "Sign in"), new_user_session_path %>
          </li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/shared/_small_navbar.html.erb
<nav class="small-navbar-wagon" role="navigation">
  <!-- navbar  -->
  <!-- navbar-default -->
  <!-- navbar-fixed-top -->
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
 <!--      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div> -->

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <!-- navbar-right -->

          <li class= "padded-right">
            <%= link_to profile_path do %>
             <%=  image_tag 'infos.png' %> Mon profil
            <% end %>
          </li>


          <% if current_user.pepeato == true %>
            <li class= "padded-right">
              <%= link_to profile_recipes_path do %>
                <%=  image_tag 'recettes.png' %> Mes recettes
              <% end %>
            </li>
          <% end %>

          <li class= "padded-right">
            <% if current_user.pepeato == true %>
              <%= link_to profile_pepeatobookings_path do %>
                <%=  image_tag 'commandes.png' %> Mes commandes
              <% end %>
              <% else %>
              <%= link_to profile_bookings_path do %>
                <%=  image_tag 'commandes.png' %> Mes commandes
              <% end %>
            <% end %>

          </li>
          <li class= "padded-right">
            <% if current_user.pepeato == true %>
              <%= link_to profile_pepeatcommunity_index_path do %>
                <%=  image_tag 'community.png' %> Pepeat community
              <% end %>
             <% end %>
          </li>

        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>