config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"



  resources :offers
  resource :profile, only: [:show, :edit, :update]

  namespace :profile do
    resources :pepeatobookings, only: [:index, :show]
    resources :bookings, only: [:index, :show, :create, :new]
    resources :pepeatcommunity
    resources :offers
    resources :recipes do
      member do
        patch :like
      end

      resources :ingredients
      resources :categories
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @recipes = Recipe.all
  end
end

app/views/home/index.html.erb
<div id="banner">
  <div class="text-center" id="big_title">
    <h2> Commandez des plats maison cuisinés par des passionnés</h2>
  </div>
  <div class="container-fluid">
    <div class="row">
      <div class="col-xs-12 col-sm-7 col-sm-offset-3">
        <%= form_tag(offers_path, method: "get", class: "form-inline") do %>
          <%= text_field_tag(:user_address, nil, placeholder: 'votre ville ?', class: 'form-control input-lg') %>
          <%= submit_tag("Search", class: "btn btn-danger btn-lg") %>
        <% end %>
      </div>
    </div>
  </div>
</div>


<div id="featured">
  <h2 class="text-center padded-bottom"> Choisissez votre camp </h2>
  <div class="container">
    <div class="row text-center">
      <div class="col-xs-12 col-sm-6">
        <div class= "card-home-presentation">
          <%= image_tag "cuistot.jpg", class: "img-center img-circle ", id: "size-picture-explaination"%>
          <h2>Pepeato</h2>
          <p> Les pepeatos sont la richesse de notre service.
            Vous voulez partager votre savoir culinaire et faire connaître vos talents du grand plublic tout en vous faisant un appoint financier ?
          <p><br> <b>Inscrivez vous comme Pepeato</b> </p></p>
          <%= link_to 'Par ici', new_user_registration_path(pepeato: true), class: "btn btn-sm btn-primary"  %>
        </div>
      </div>
      <div class="col-xs-12 col-sm-6">
        <div class= "card-home-presentation">
         <%= image_tag "user.png", class: "img-center img-circle", id: "size-picture-explaination"%>
          <h2>Pepeato seeker</h2>
          <p> Vous n'avez pas le temps de faire à manger ou vous n'avez simplement pas l'envie ? Vous cherchez néanmoins des plats maison de qualités cuisinés par des gens dont vous pouvez avoir confiance ? </p>
          <p><br> <b>Inscrivez vous comme Pepeato seeker</b> </p></p>
          <%= link_to 'Par ici', new_user_registration_path, class: "btn btn-sm btn-primary"  %>
        </div>
      </div>
    </div>
  </div>
</div>



<div id="userstories" class="text-center">
  <h2 class="text-center" id="title-talk">DES GOUTS ET DES COULEURS </h2>
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-9">
        <div class=" text-center god">
          <div class="title-card-feat">
            Voir les plats à Paris
          </div>
          <%= link_to offers_path(user_address: "Paris")  do %>
            <%=image_tag "Paris.jpg", class: "size_img-home" %>
          <% end %>
        </div>
      </div>
       <div class="col-xs-12 col-sm-3 ">
        <div class="title-card-feat-lille">
            Voir les plats à lille
          </div>
        <%= link_to offers_path(user_address: "Lille") do %>
            <%=image_tag "lille.jpg", class: "size_img-home img-right-feat" %>
          <% end %>

      </div>
    </div>
  </div>
</div>