config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"



  resources :offers
  resource :profile, only: [:show, :edit, :update]

  namespace :profile do
    resources :pepeatobookings, only: [:index, :show]
    resources :bookings, only: [:index, :show, :create, :new]
    resources :pepeatcommunity
    resources :offers
    resources :recipes do
      member do
        patch :like
      end

      resources :ingredients
      resources :categories
    end
  end

end

app/models/offer.rb
# == Schema Information
#
# Table name: offers
#
#  id         :integer          not null, primary key
#  recipe_id  :integer
#  portion    :integer
#  startdate  :datetime
#  enddate    :datetime
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  price      :integer
#  delay      :string
#
# Indexes
#
#  index_offers_on_recipe_id  (recipe_id)
#

class Offer < ActiveRecord::Base
  belongs_to :recipe
  has_many :bookings

  validates :portion, presence: true
  validates :startdate, presence: true
  validates :enddate, presence: true
  validates :price, presence: true
  validates :delay, presence: true
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  def index
    @recipes = Recipe.joins(:user).all
    @booking = Booking.new

    if params[:user_address]
      @users = User.near(params[:user_address])
      @recipes = []
      @users.each { |user| @recipes << user.recipes }
      @recipes = @recipes.flatten
    end

    # select * from recipes
    # inner join users on users.id = recipes.user_id
    # where users.address = "zert"
    @markers = Gmaps4rails.build_markers(@recipes) do |recipe, marker|
      marker.lat recipe.user.latitude
      marker.lng recipe.user.longitude
    end
  end

  def show
    @booking = Booking.new
    @offer = Offer.find(params[:id])
    @recipe = @offer.recipe
   # select recipes_id from recipes
   # inner join users on users.id = recipes.user_id
   # where users.id = recipes.user_id
  end
end

app/controllers/profile/offers_controller.rb
module Profile
  class OffersController < ApplicationController
    def index
      @offers = Offer.all
    end
    def new

      @offer = Offer.new
    end
    def create
       @offer = current_user.offers.new(offer_params)

      if @offer.save
        redirect_to profile_recipes_path
      else
        render :new
      end
    end

    def destroy
      @offer = current_user.offers.find(params[:id])
      @offer.destroy
      redirect_to profile_recipes_path
    end

    def offer_params
       params.require(:offer).permit(:recipe_id, :startdate, :enddate, :portion, :delay, :price)
    end
  end
end

app/helpers/offers_helper.rb
module OffersHelper
  def available_portions(offer)
    offer.portion - booked_portions(offer)
  end

  def booked_portions(offer)
    offer.bookings.sum(:quantity)
  end
end

app/views/offers/index.html.erb
<div id="map" class="map"></div>

<div class="results-container">
  <div class="container-fluid">
    <div class="row">
      <% @recipes.each do |recipe| %>
        <% recipe.offers.each do |offer| %>
          <div class= "card-padding-map">
            <div class="col-xs-12 col-sm-4 padded-bottom">
              <div class="card-recipe">
                <div class="card-recipe-header" style="background-image: url('<%= asset_path offer.recipe.picture.url(:medium) %>');">
                  <div class="card-recipe-filter"></div>
                  <div class="card-recipe-header-infos">
                    <h3><%= offer.recipe.name %></h3>
                  </div>
                  <div class="card-recipe-header-portions">
                    <%= available_portions(offer) %> x parts
                  </div>
                  <div class="card-recipe-header-price">
                    <%= offer.price || "-" %> €
                  </div>
                </div>
                <div class="card-recipe-body">
                  <div class="row">
                    <div class="col-xs-3">
                      <%= image_tag offer.recipe.user.picture.url(:medium), class: "img-circle img-index" %>
                    </div>
                    <div class="col-xs-9">
                      <h3>
                        <%= offer.recipe.user.firstname.capitalize %> <%= offer.recipe.user.lastname.capitalize %>
                      </h3>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-xs-12 text-center">
                      <p class="card-recipe-pickup">
                        <%= day_in_french(offer.startdate) %> <br>
                        <%= offer.startdate.strftime('%Hh%M')%> à <%= offer.enddate.strftime('%Hh%M') %>
                      </p>
                    </div>
                  </div>
                </div>

                <div class="footer text-right">
                  <ul class="list-inline">
                    <li>
                      <a data-toggle="modal" data-target="#booking-<%=offer.id%>" class="card-recipe-control">
                        <b>Commander</b>
                      </a>
                    </li>
                    <li>
                      <%= link_to offer_path(offer), class: "card-recipe-control" do %>
                        <i class="fa fa-eye"></i>
                      <% end %>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>

          <!--modale booking-->
          <div class="modal fade" id="booking-<%=offer.id%>">
            <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                  <h4 class="modal-title text-center"><%= offer.recipe.name %></h4>
                </div>
                <div class="modal-body">
                  <%= simple_form_for [offer, @booking], url: profile_bookings_path do |f| %>
                    <%= f.input :quantity, label: 'Combien de parts ?', collection: 1..available_portions(offer), input_html: {class: "input-lg"}, prompt: "aucune part choisie" %>
                    <%= f.input :offer_id, as: :hidden, :input_html => { :value => offer.id }%>
                    <% if available_portions(offer) > 0 %>
                      <%= f.button :submit, label: 'Réservez maintenant', class: "btn btn-success btn-lg" %>
                    <% else %>
                      <p> Désolé, toutes les parts ont été vendues :) </p>
                    <% end %>
                  <% end %>
                </div>
              </div><!-- /.modal-content -->
            </div><!-- /.modal-dialog -->
          </div><!-- /.modal -->
        <% end %>
      <% end %>
    </div>
  </div>
</div>


<% content_for(:after_js) do %>
  <%= javascript_tag do %>
    $(document).on('ready', function() {
      handler = Gmaps.build('Google');
      handler.buildMap({ internal: { id: 'map' } }, function(){
        markers = handler.addMarkers(<%= raw @markers.to_json %>);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
      });
    })
  <% end %>
<% end %>

app/views/offers/show.html.erb
<div id="bgshowrecipe">
  <h1 class="text-center title-show"><%= @recipe.name.upcase%></h1>
  <%= image_tag @recipe.user.picture.url(:medium), class: "img-circle img-pos-bg" %>
</div>
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-5">
      <div class="card">
        <p><b>Nombre de personne(s) : </b><%=@recipe.numberpers%></p>
        <p><b>Temps de cuisson : </b><%=@recipe.cooktime%></p>
        <p><b>Temps de préparation : </b><%=@recipe.preparationtime%></p>
      </div>
      <div class="col-xs-12 col-sm-5">
       <%= image_tag @recipe.picture.url(:medium), class: 'img-recipe' %>
      </div>
      <div class="col-xs-12">
        <div class="card">
          <div class= "small-padded-bottom">
            <b>ingredients :</b>
          </div>
          <p>- 3 oeufs </br>
          - 1/4 de litre de lait </br>
          - 10 cl de crème fraîche  </br>
          - 2 grosses cuillères à soupe de farine  </br>
          - 100 g de gruyère râpé  </br>
          - 4 tranches de jambon (peuvent être remplacées par des lardons ou encore des épinards)  </br>
          - sel et poivre  </br>
          </p>

        </div>
      </div>
    </div>
    <div class="col-xs-12 col-sm-5">
      <div class="large-card">
        <p><b>Recette:</b>
        <div>
          <%=@recipe.description%></p>
        </div>
      </div>
    </div>
    <div class="col-xs-12 col-sm-2">
        <div class="col-xs-12">
          <div class='padding-soft '>
            <div class= "small-padded-bottom">
            Recette crée le
            <strong>
              <%= day_in_french(@recipe.created_at)%>
              <%= @recipe.created_at.strftime('%M/%m')%>
              à <%= @recipe.created_at.strftime('%Hh%M')%>
            </strong>
            </div>
            <div class= "padded-bottom">
            Par : <strong><%= @recipe.user.firstname.upcase %> <%= @recipe.user.lastname.upcase %></strong>
            </div>
          </div>
        </div>
    </div>
  </div>
</div>